:PROPERTIES:
:ID:       b8d0b205-e280-48ca-ac52-8863056aba93
:END:
#+title: Functional programming

One of the main concepts about this paradigm is [[id:fff13688-0b15-4836-a901-588ac28524a0][Lambda Calculus]].

Functional programming is based on expressions that include variables or
constant values, expressions combined with other expressions, and functions.

* Referential transparency
Means that give the same function, the same values to evaluate, will always return
the same result in pure functional programming, as they do in math.

* Links
+ [[https://chadnauseam.com/coding/random/how-side-effects-work-in-fp/][How side effects works in FP]]
+ [[https://github.com/BartoszMilewski/DaoFP][The Dao of Functional Programming]]

* Questions
** What is =pattern matching=?
Is a dispatch mecanism. Choosing which variant of a function is the correct one to
call. It's inspired by standard mathematical notations. Some of the pros of this feature is:

- Can make an assertio based on the value and the structure of something.
