* Uma tentativa de um digital garden
Esse repositório, num futuro próximo (talvez) deva sofrer mudanças, incluindo
a internacionalização das notas aqui presentes. Por enquanto, as notas serão
produzidas em português do Brasil.

(Isso é um lembrete para mim também: no futuro isso *PRECISA* estar em inglês!)

** O que é este repositório?
Esse repositório foi inspirado na construção de uma wiki apostando no
[[https:www.swyx.io/learn-in-public/][Learn in Public]], seguindo conceitos
propostos pela metáfora do "jardim digital". Não existe um conceito concreto
na comunidade a respeito do que é, mas entenda que é algo próximo a um modelo
do qual tem-se o foco no processo de aprendizado e não no resultado final.
Caso queira se aprofundar no assunto, recomendo tais leituras:

- [[https:joelhooks.com/digital-garden][Digital Garden - Joel Hooks]]
- [[https:maggieappleton.com/garden-history][A Brief History & Ethos of the Digital Garden - Maggie Appleton]]

Esse repositório tem inspiração direta nos seguintes repositório: [[github:nikitavoloboev/knowledge][
nikitavoloboev/knowledge]]. Você consegue achar outras inspirações em:
[[github:KasperZutterman/Second-Brain][KasperZutterman/Second-Brain]] e [[github:MaggieAppleton/digital-gardeners][MaggieAppleton/digital-gardeners]]. Em ambos
repositórios estão reunindo exemplos e materiais para construção do seu
próprio jardim digital.

** Contribuições
Qualquer contribuição é bem-vinda! Se tiver alguma dúvida sinta-se a vontade
pra abrir uma issue, caso tenha achado algo errado (no mínimo detalhe que seja),
não fique inibido de abrir um pull request. A ajuda de qualquer pessoa é
válida e altamente incentivada! =)
